sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: YCc9iBezeH+2orEQ+68Mj5Az27QDbGimPZzASwwcuo5qEzHG2JvKYhixQH333Cdh4urqcaHwA3ZGQEs6ZIaO+glfX4VfWek8CrUttBTUMaymBQkTLKfrrvZ+Lrjlhe8aJ7B7Bcfl9nyZkpeqvQOkfnBbPchwI2KYy0zen/O9ipBLAqT4z/GKGgaZVoUDsVWRVT6+7qMtsSht0epyQQt0iuQZdWyHannb2BAogpWQwKjZmBMYbsl6Gi1NxbrHqo1Ul4mZpKPJ79g86xaKwMqYO9AKnp0ypLXf7DQeTNTUWTTJO1VcwvsIgDz8STR0wxQ3FKcVcNmHU9eHOioAlrr/hgEZuT+c4Gj/IW8SuVr+ETQXJlvWIVWPNzJwcKIpY4O4D3Y69TF877Z/u2QPulijhIE8eIrNC8lGzOdVHAZe+vAYRwX5fywZQ5Wor96Jg1+2NJ8RZOS4XF/rMdyrvTXVlzUjS150yZWaRJtC0vQM+O1ojfjxvZD/4iVroTzYjlo1cu1ctnYjjwqYwdhY2MgRL30Nn0adMvI8CWAXT9U1Q/gllMrwrOYBL7ETQmO/7mQyBXdhXse3uwm1Ug6gXzDa5OTW1PWev9D5O8p8k8DGA3SLbHTkcvi02hC7tQJAlBAtuEGwzM/ArtWKnYVHyeW3hNxcZ3VzDySC9ijLHvdyph8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Franse-Toestanden_2839
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy